# Generated by Django 4.0.2 on 2022-03-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='popular',
            new_name='ratings',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Dhaka,Bangladesh', 'Dhaka Bangladesh'), ('Banani,Bangladesh', 'Banani Bangladesh'), ('Jatrabari,Bangladesh', 'Jatrabari Bangladesh'), ('Motijheel,Bangladesh', 'Motijheel Bangladesh'), ('Mohammadpur,Bangladesh', 'Mohammadpur Bangladesh'), ('Gulshan,Bangladesh', 'Gulshan Bangladesh'), ('Badda,Bangladesh', 'Badda Bangladesh'), ('Khilgaon,Bangladesh', 'Khilgaon Bangladesh'), ('Tejgaon,Bangladesh', 'Tejgaon Bangladesh'), ('Rampura,Bangladesh', 'Rampura Bangladesh'), ('Banasree,Bangladesh', 'Banasree Bangladesh'), ('Malibagh,Bangladesh', 'Malibagh Bangladesh'), ('Mouchak,Bangladesh', 'Mouchak Bangladesh'), ('Shahbag,Bangladesh', 'Shahbag Bangladesh'), ('Paltan,Bangladesh', 'Paltan Bangladesh'), ('Mohakhali,Bangladesh', 'Mohakhali Bangladesh'), ('Mirpur,Bangladesh', 'Mirpur Bangladesh'), ('Kalabagan,Bangladesh', 'Kalabagan Bangladesh'), ('Kathalbagan,Bangladesh', 'Kathalbagan Bangladesh'), ('Dhanmandi,Bangladesh', 'Dhanmandi Bangladesh'), ('Uttara,Bangladesh', 'Uttara Bangladesh'), ('Azimpur,Bangladesh', 'Azimpur Bangladesh'), ('Aminbazar,Bangladesh', 'Aminbazar Bangladesh'), ('Nikunja,Bangladesh', 'Nikunja Bangladesh'), ('Wari,Bangladesh', 'Wari Bangladesh'), ('Shyamoli,Bangladesh', 'Shyamoli Bangladesh'), ('Lalmatia,Bangladesh', 'Lalmatia Bangladesh'), ('Gabtoli,Bangladesh', 'Gabtoli Bangladesh'), ('Khilkhet,Bangladesh', 'Khilkhet Bangladesh'), ('Demra,Bangladesh', 'Demra Bangladesh'), ('Bashabo,Bangladesh', 'Bashabo Bangladesh'), ('Bailyroad,Bangladesh', 'Bailyroad Bangladesh'), ('Zigatola,Bangladesh', 'Zigatola Bangladesh'), ('Modhubag,Bangladesh', 'Modhubag Bangladesh'), ('Mugda,Bangladesh', 'Mugda Bangladesh')], max_length=50),
        ),
    ]
