# Generated by Django 3.2.6 on 2022-03-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_popular_product_ratings_alter_customer_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsplaced',
            old_name='rooms',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='rooms',
            new_name='quantity',
        ),
    ]
