# Generated by Django 3.2.6 on 2022-04-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attractions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attractions',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('L', 'Luxury'), ('CD', 'Cheap Deals'), ('C', 'Car Rentals'), ('B', 'Bike Rentals'), ('P', 'Popular Attractions')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(blank=True, default=''),
        ),
    ]
